app/controllers/docs.py
# Controller for help-info-settings
from flask import *
import json
from config import VERSION_FILE

docs = Blueprint('docs', __name__, template_folder='templates', static_folder='static')

@docs.route('/help', methods=['GET', 'POST'])
def main_route():
	
	return render_template('docs.html', **data)

app/controllers/gradeView.py
from flask import *
from gridProcessing import *
from sqlFunctions import *
from os import listdir
from PIL import Image
import os
import config as C
import datetime
import util

gradeView = Blueprint('gradeView', __name__)
VERSION_FILE = C.VERSION_FILE

NUM_NORM_PREV = 5


	

# Requires: the imgId in the database
# Effects: forms list of data needs for a page
def getPageData(imgId):

	user = session['username']
	
	image = getImageData(imgId)
	if image is None:
		return False
	gridData = getGridData(imgId)
	gradeSession = getUnfinishedGradesFromUser(user, imgId=imgId)
	associatedFeatures = getOptions()

	imgSrc, gridSrc = util.getImagePath(imgId)
	
	data = {
		'img' : image,
		'imgSrc': url_for('content', filename=imgSrc),
		'gridSrc': url_for('content', filename=gridSrc),
		'numPrev' : NUM_NORM_PREV, #number of control images to show at once
		'xOffset' : gridData['xOffset'],
		'yOffset' : gridData['yOffset'],
		'gridScaleRatio': gridData['scaleRatio'], 
		'gitVersion' :  open(VERSION_FILE, 'r').readline().replace('\n', ''),
		'gradeSessions': gradeSession,
		'associatedFeatures': associatedFeatures
	}

	return data



@gradeView.route('/grade', methods=['GET', 'POST'])
def main_route():

	if 'username' not in session:
		return redirect(url_for('user.login_route'))

	gradeView = True
	data = {}

	if request.method == 'GET' and request.args:
		args = request.args
		imgId = args['p']
		print('\nLoading view for', imgId, '\n')
		data = getPageData(imgId)


	if not request.args or data == False: #data == false means no imgid found in db
		
		return redirect(url_for('main.main_route'))


	return render_template('gradeView.html', **data)





@gradeView.route('/getUser', methods=['GET', 'POST'])
def get_user_route():
	rForm = request.form
	if request.form['caller'] == 'exportGrade':
		user = session['username']
		return jsonify({'user': user})
	else: return jsonify({'user':'error'})

app/controllers/main.py
from flask import *
import json
import gridProcessing
import sqlFunctions as sql
import config as C
import hashlib
import os

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def main_route():

	data = {
		'version' : C.GIT_TAG
	}

	if 'username' not in session:
		return redirect(url_for('user.login_route'))

	currentImages = sql.getCurrentImages(session['username'])

	data['currentImages'] = currentImages

	return render_template('index.html', **data)


@main.route('/gallery', methods=['GET', 'POST'])
def gallery_route():
	if 'username' not in session:
		return redirect(url_for('user.login_route'))

	category = None

	if not request.form and not request.args:
		return redirect(url_for('gradeView.main_route'))

	if request.args and 'category' in request.args:
		category = request.args['category']

	images = []
	if category:
		images = sql.getImages(category=category)
	else:
		images = sql.getImages(category=C.imgCategories['patient'])

	imageGrades = {}
	currentImageGrades = {}
	isImageGraded = {}
	for i in images:
		imgId = i['imgId']
		finishedGrades = sql.getFinishedGrades(imgId)
		finishedGrades = [x['userId'] + ' - Session ' + str(x['sessionId']) + ' finished ' + x['timestamp'] for x in finishedGrades]
		currentGraders = sql.getGradeInfoForImage(imgId, excludeFinished=True)

		currentImageGrades[imgId] = currentGraders
		imageGrades[imgId] = finishedGrades
		if currentGraders or finishedGrades:
			isImageGraded[imgId] = True
	
	#print '\n\n\n\n', imageGrades, '\n\n\n'
	data = {
		'images' : images,
		'isImageGraded': isImageGraded,
		'finishedGraders': imageGrades,
		'currentGraders': currentImageGrades,
		'category' : category
	}


	return render_template('gallery.html', **data)

app/controllers/review.py
from flask import *
import json
import gridProcessing
import sqlFunctions as sql
import config as C
import hashlib
import os
import util
import gradeData

review = Blueprint('review', __name__)


@review.route('/review', methods=['GET', 'POST'])
def main_route():
	if 'username' not in session:
		return redirect(url_for('user.login_route'))


	data = {
		'imgSrc': url_for('content', filename=C.FILE_PATHS['grid']['analysis']),
		'gridSrc': ''
	}

	return render_template('review.html', **data)


@review.route('/overview', methods=['GET', 'POST'])
def overview_route():
	if 'username' not in session:
		return redirect(url_for('user.login_route'))

	# api, on front end: get all grade files that are finished

	return render_template('overview.html')


@review.route('/downloadFinished', methods=['GET', 'POST'])
def download_route():
	if 'username' not in session:
		return redirect(url_for('user.login_route'))

	if 'master' in request.args:
		filepath = gradeData.generateMasterCSV()
		return send_file(filename_or_fp=filepath, as_attachment=True, attachment_filename=filepath.split('/')[-1])

	# api, on front end: get all grade files that are finished
	return render_template('download.html')

app/controllers/uploads.py
from flask import *
from gridProcessing import *
from sqlFunctions import *
import hashlib
import os
from os import listdir
from os.path import isfile, join
from PIL import Image
import config as C
import math
import uuid
import util
import shutil

uploads = Blueprint('uploads', __name__)


THUMBNAIL_PATH = C.FILE_PATHS['thumbnails']


# Effects: returns a extension name if it is valid
def getExtension(filename):
	ext = filename.rsplit('.', 1)[1]
	if ext.lower() in C.ALLOWED_EXTENSIONS:
		return ext
	else:
		return ''



# Effects: returns filename in the format [username]_[albumname]_[md5(prevString)]
#TODO: doesnt do effects above?
def generateFilename(filename):
	return str(uuid.uuid4())[:13]


# Requires: request object, type of img upload (patient or normal)
# Effects: Uploads valid file to server and updates database
def uploadImg(request, category):
	form = request.form
	upFolder = ''
	# type
	if category == C.imgCategories['control']:
		upFolder = C.FILE_PATHS['control']
	elif category == C.imgCategories['patient']:
		 upFolder = C.FILE_PATHS['patient']

	# check if the post request has the file part
	if 'img' not in request.files:
		flash('No file part')
		print('failed: ', request.files)
		return redirect(request.url)
	fileObj = request.files['img']
	
	fileExt = getExtension(fileObj.filename)

	if fileObj and fileExt: # If file and extension aren't null
		filename = generateFilename(fileObj.filename)

		side = form['side']
		refName = ''
		comments = ''

		if form['refName']:		
			refName = form['refName']
		if form['comments']:
			comments = form['comments']
		


		# save to database
		insertImageToDB(fileExt, filename, refName, side, comments, category)
		# save to server
		filepath = os.path.join(upFolder, filename + '.' + fileExt)
		fileObj.save(filepath)
		# backup of original
		shutil.copy(filepath, os.path.join(upFolder, 'original'))
		
		# make thumbnail
		thumb = Image.open(os.path.join(upFolder, filename + '.' + fileExt))
		thumb.thumbnail((500,500), Image.ANTIALIAS)
		thumb.save(os.path.join(THUMBNAIL_PATH, filename + '.' + fileExt))
		print('Successful image upload:', filename, category)
	return filepath, filename




@uploads.route('/uploads', methods=['GET', 'POST'])
def main_route():

	if 'username' not in session:
		return redirect(url_for('user.login_route'))

	isUploaded = False
	category = ''
	folderPath = ''
	imgPath = ''
	imgId = ''
	form = None
	
	if request.method == 'GET':
		if request.args:
			category = request.args['category']
	# Add or delete album
	if request.method == 'POST':
		form = request.form
		
		if request.files:
			operation = form['op']
			category = form['category']
			if operation == 'add':
				isUploaded = True
				try:
					imgPath, imgId = uploadImg(request, category)
				except IOError as e:
					isUploaded = False
					print(e)
					print('Error uploading file of category', category)

				if category == C.imgCategories['patient']:
					folderPath = C.FILE_PATHS['patient']
				elif category == C.imgCategories['control']:
					folderPath = C.FILE_PATHS['control']
		elif 'op' in form and form['op'] == 'delete':
			util.deleteImg(form['imgId'])
			return redirect(url_for('gradeView.main_route'))
			


	data = {
		'category' : category,
		'uploaded' : isUploaded,
		'imgSrc' : imgPath,
		'imgId' : imgId
	}


	return render_template('uploads.html', **data)


# Requires: PIL image, two coordinates
# Effects: calculates angle between vectors, rotates image around orginCoords
# returns rotated image
# fovea coords should be close to center (optos images are centered on fovea)
def rotateImage(img, foveaCoords, discCoords):
	# get angle between vectors
	# rotate image -angle
	print(foveaCoords, discCoords)
	angle = math.atan2(discCoords[1] - foveaCoords[1], discCoords[0] - foveaCoords[0])
	degr = math.degrees(angle)
	if discCoords[0] < foveaCoords[0]:
		degr += 180
	# since PIL.Image.rotate will rotate around center of image,
	# we need to put our rotation origin point at the center of the image,
	# rotate, then crop the image back to normal size

	imgW, imgH = img.size
	pixFromCenterX = int(foveaCoords[0] - (imgW / 2))
	pixFromCenterY = int(foveaCoords[1] - (imgH / 2))
	paddedImgWidth = abs(pixFromCenterX) + imgW
	paddedImgHeight = abs(pixFromCenterY) + imgH

	pasteX = 0
	pasteY = 0
	if pixFromCenterX < 0:
		pasteX += abs(pixFromCenterX)
	if pixFromCenterY < 0:
		pasteY += abs(pixFromCenterY)

	rgba = img.split()
	padImg = Image.new('RGB', (paddedImgWidth, paddedImgHeight))
	padImg.paste(img, (pasteX, pasteY))

	padImg = padImg.rotate(degr)

	finalImg = padImg.crop((pasteX, pasteY, imgW+pasteX, imgH+pasteY))
	return finalImg, degr


# Requires: FA image and grid images are their proper sizes, name of picture in database,
# img file format, and the percentage offsets created by the user positioning data
# Effects: puts the center of the grid on the specified location of the FA image, and scales grid
# according to opticDisk <--> fovea position
def createGriddedImage(foveaCoords, discCoords, imgId, category, insertToDB=True):

	# Determine save path
	if category == C.imgCategories['control']:
		uploadPath = C.FILE_PATHS['control']
	else:
		uploadPath = C.FILE_PATHS['patient']

	filepath = util.getImagePath(imgId)[0]
	faImg = Image.open(filepath)
	fa_w, fa_h = faImg.size
	grid = Image.open(C.FILE_PATHS['grid']['display'], 'r')

	# Scale grid
	# currently arbitrary, but works relative to all uploads
	foveaToDisk = 4.0 #mm
	eyeWidth = 24.0 #mm, typical eye diameter
	percentDist = (foveaToDisk / eyeWidth) * .57

	distance = abs(math.hypot(foveaCoords[0] - discCoords[0], foveaCoords[1] - discCoords[1]))	
	gridWidth = distance / percentDist
	gridHeight = (gridWidth / grid.size[0]) * grid.size[1]
	gridHeight = int(gridHeight)
	gridWidth = int(gridWidth)
	scaleRatio = gridWidth / float(grid.size[0])

	grid = grid.resize((gridWidth, gridHeight), Image.ANTIALIAS)
	
	
	# Calculate where grid goes and paste
	offset = (int(foveaCoords[0] - (gridWidth / 2)), int(foveaCoords[1] - (gridHeight  / 2)))
	# ^^ offsetting the scaled grid, so using gridWidth and gridHeight
	rgba = grid.split()
	alpha = rgba[len(rgba)-1]

	croppedGrid = Image.new('RGBA', (fa_w, fa_h))
	croppedGrid.paste(grid, offset, mask=alpha)

	gridId = C.GRID_PREFIX + imgId + C.GRID_FORMAT
	if insertToDB == True:
		insertGridToDB(gridId, offset[0], offset[1], imgId, scaleRatio, discCoords[0], 
			discCoords[1], foveaCoords[0], foveaCoords[1])
	png_info = grid.info
	croppedGrid.save(os.path.join(uploadPath, gridId), **png_info)

	print('Success processing image and grid:', gridId, 'scaleRatio=', scaleRatio)

	# save version of grid for OpenCV contours
	#contourGrid = Image.new('RGB', faImg.size, (255,255,255))
	#contourGrid.paste(grid, offset, grid)
	#contourGrid = contourGrid.convert('L') # convert to grayscale
	#contourGrid = contourGrid.point(lambda x: 0 if x<200 else 255, '1') #convert to black and white
	#contourGrid.save(C_GRID_PATH, 'JPEG')
	return os.path.join(uploadPath, gridId)


@uploads.route('/uploads/position', methods=['GET', 'POST'])
def upload_position_route():
	rForm = request.form
	imgId = rForm['picName']
	image = getImageData(imgId)
	foveaCoords = [rForm['foveaX'], rForm['foveaY']]
	foveaCoords = list(map(int, foveaCoords))
	discCoords = list(map(int, [rForm['discX'], rForm['discY']]))

	#TODO: reduce database calls / img opens

	filepath = util.getImagePath(imgId)[0]
	faImg = Image.open(filepath)
	faImg, degrees = rotateImage(faImg, foveaCoords, discCoords)
	faImg.save(filepath)

	newImgPath = createGriddedImage(foveaCoords, discCoords, imgId, rForm['category'])

	return jsonify({'success': 'sucess'})

app/controllers/user.py
from flask import *
import json
import gridProcessing
import sqlFunctions as sql
import config as C
import hashlib
import os
import util

user = Blueprint('user', __name__)


@user.route('/account', methods=['GET', 'POST'])
def main_route():
    
	return 'hello ' + session['username']


@user.route('/login')
def login_route():
    if 'REMOTE_USER' in request.environ: # TODO: make sure they actually signed in with cosign
        session['username'] = request.environ['REMOTE_USER']
    elif C.DEV_USER:
        session['username'] = C.DEV_USER
    else:
        return 'You do not have access'

    return redirect(url_for('main.main_route'))

@user.route('/logout')
def logout_route():
    cosignUrl = 'https://weblogin.umich.edu/cgi-bin/logout'
    session.pop('username')
    return redirect(cosignUrl)


# give warning when opening same image in multiple tabs

app/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<link rel="stylesheet" href="{{url_for('static', filename='css/jquery-ui.min.css')}}"/>
	<link rel="stylesheet" href="{{url_for('static', filename='css/global.css')}}"/>	
	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}"/>
	<link rel="stylesheet" href="{{url_for('static', filename='css/uploads.css')}}"/>
	{% block css %}{% endblock %}

	<title>{% block title %}ISLA{% endblock %}</title>
</head>

<body>
	  <div id="fullwrap">

		<div id ="topmenu">
			<div class="wrap-men-el">
				<a class="men-el" href="{{ url_for('main.main_route') }}">Home</a>
				<a class="men-el" href="{{ url_for('main.gallery_route', category='patient') }}">Grade</a>
				<a class="men-el" href="{{ url_for('uploads.main_route') }}">Upload</a>
			</div>
	
			<div class="wrap-men-el" id="topmenu-tools">
				<div id="toolbarLabel"><span>Toolbar:</span></div>
				{% block toolbar %}
				{% endblock %}
			</div>
	
			<div class="wrap-men-el">
				<a class="men-el" href="{{ url_for('user.main_route') }}">Account</a>
				<a class="men-el" href="{{ url_for('user.logout_route') }}">Logout</a>
			</div>
		</div>

		<div id="content">
			{% block content %}{% endblock %}
		</div>
		<div id="footer">
			{% block footer %}{% endblock %}
		</div>
	  </div>


<script src="{{url_for('static', filename='js/jquery-3.1.1.min.js')}}"></script>
<script src="{{url_for('static', filename='js/jquery-ui.min.js')}}"></script>

{% block js %}
{% endblock %}
</body>

</html>

app/templates/docs.html
{% extends "base.html" %}
{% block content %}
<div id="" class="">
		<h1>Shortcuts</h1>
		<p>Right Arrow: Next Normal Image</p>
		<p>Left Arrow: Previous Normal Image</p>
		<p>On number row</p>
		<p>1 key: Submit Grade Option 1</p>
		<p>2 key: Submit Grade Option 2</p>
		<p>3 Key: Submit Grade Option 3</p>
		<hr>
		<h1>Tips</h1>
		<p>To turn hover mode back on, click on the cell that is currently graded to "unlock" it</p>
		<hr>
		<p>Git Release: {{version}}</p>
		<p>Maverick Cook, Dr. Andrew DeOrio</p>
</div>
{% endblock %}

app/templates/download.html
{% extends "base.html" %}
{% block content %}
<div id="holder" class="">
    
</div>
{% endblock %}

{% block js %}
<script src="{{url_for('static', filename='js/download.js')}}"></script>
{% endblock %}

app/templates/gallery.html
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" href="/static/css/index.css" />
{% endblock %}
{% block content %}


	{% for p in images %}
	<div class="imgCont">
		{% set src = url_for('content', filename='uploads/thumbnails/' + p['imgId'] + '.' + p['format']) %}
		{% if category == 'patient' %}
		<form class="deleteImg" action="{{ url_for('uploads.main_route') }}" method="POST" enctype="multipart/form-data">
			<input type="hidden" name="op" value="delete">
			<input type="hidden" name="imgId" value="{{p['imgId']}}">
			<input type="submit" value="X">
		</form>
		<a href="grade?p={{p['imgId']}}" class="aPrev">
			<div id="imgPrev{{loop.index}}" class="imgPrev">
				<img src="{{ src }}">
			</div>
			{% if p['referenceName'] %}
			<p>Reference Name: {{ p['referenceName'] }}</p>
			{% endif %}
			<p>UUID: {{ p['imgId'] }}</p>
		</a>
		{% if isImageGraded[p['imgId']] %}
				<div class="wrap-menu" style="width:100%">
					<button class="dark-button">Grading Info</button>
					<div class="wrap-drop-down" style="background-color:#eee">
						<div class="drop-down"><!-- TODO: remove inline -->
							<h4>Users currently grading:</h4>
							<ul>
								{% for g in currentGraders[p['imgId']] %}
								<li>{{ g['userId'] }} - Session {{ g['sessionId']}}</li>
								{% endfor %}
							</ul>
							{% if finishedGraders[p['imgId']] %}
							<h4>Users finished grading:</h4>
							<ul>
								{% for g in finishedGraders[p['imgId']] %}
								<li>{{g}}</li>
								{% endfor %}
							</ul>
							{% endif %}
						</div> <!-- END .wrap-graders-dropdown-list -->
					</div>
				
				</div>
			{% else %}
				<button class="dark-button">No grading data</button>
			{% endif %}
		{% else %}
			<div id="imgPrev{{loop.index}}" class="imgPrev">
				<img src="{{ src }}">
			</div>
		{% endif %}

		
	</div>
	{% endfor %}
{% endblock %}

{% block js %}
<script src="{{url_for('static', filename='js/gallery.js')}}"></script>
{% endblock %}

app/templates/help-info-settings.html
{% extends "base.html" %}
{% block content %}
<div id="" class="">
		<h1>Shortcuts</h1>
		<p>Right Arrow: Next Normal Image</p>
		<p>Left Arrow: Previous Normal Image</p>
		<p>On number row</p>
		<p>1 key: Submit Grade Option 1</p>
		<p>2 key: Submit Grade Option 2</p>
		<p>3 Key: Submit Grade Option 3</p>
		<hr>
		<h1>Tips</h1>
		<p>To turn hover mode back on, click on the cell that is currently graded to "unlock" it</p>
		<hr>
		<p>Git Release: {{version}}</p>
		<p>Maverick Cook, Dr. Andrew DeOrio</p>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}

<div id="wrap-home" class="">

	<h1>Hello, {{session['username']}}</h1>

	<div>
		<h2>Continue Grading</h2>
		<p>Images where you have one or more open grading sessions</p>
		{% for x in currentImages %}
			<a class="toGradeLink" href="{{ url_for('gradeView.main_route', p=x['imgId']) }}">{{ x['referenceName'] }}</a>
		{% endfor %}
	</div>
	
	<br>
	<hr>

	<div id="banner">
		<div class="blob">
			<a href="{{ url_for('main.gallery_route', category='patient') }}"><p>Grade</p>
		</div>
		<div class="blob">
			<a href="{{ url_for('uploads.main_route') }}"><p>Upload</p></a>
		</div>
	</div>

	<br>

	<h2>Grading Shortcuts</h2>
	<ul>
		<li>Right Arrow Key: Next Cell</li>
		<li>Left Arrow Key: Previous Cell</li>
		<li>Up Arrow Key: Next control image</li>
		<li>Down Arrow Key: Previous control image</li>
		<li>Enter Key: Submit cell grade</li>
	</ul>
	<p>On number row</p>
	<ul>
		
		<li>1 key: Select Grade Option 1</li>
		<li>2 key: Select Grade Option 2</li>
		<li>3 Key: Select Grade Option 3</li>
		<li>4 Key: Select Grade Option 4</li>
	</ul>
	
	<hr>
	<p>Git Release: {{version}}</p>
	<p><a href="http://mavcook.com">Maverick Cook</a>, <a href="http://www.andrewdeorio.com/">Dr. Andrew DeOrio</a></p>
</div>
{% endblock %}

app/templates/overview.html
{% extends "base.html" %}
{% block content %}
<div id="" class="">
		1. bar chart of percentage of x grade (perfused, non perfued, ungradeable)
		2. bar chart of counts/percentage of grades per cell (cell 1 = 30% perfused, 20% ungradeable, etc)
		3. gradable: 

</div>

<!-- reload / new request-->
<select multiple name="graders">
	{% for grader in graders %}
	<option value="{{ grader }}">{{grader}}</option>
	{% endfor %}
</select>

<select multiple name="images">
	{% for i in images %}
	<option value="{{ i['imgId'] }}">{{i['referenceName']}}</option>
	{% endfor %}
</select>

<!-- Live changes -->
<!-- TODO: grade options from somewhere -->
<input type="radio" name="grade" value="all"> Perfused<br>
<input type="radio" name="grade" value="female"> Female<br>
<input type="radio" name="grade" value="other"> Other

{% endblock %}

{% block js %}
<script src="{{url_for('static', filename='js/overview.js')}}"></script>
{% endblock %}

app/templates/uploads.html
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" href="/static/css/index.css" />
<link rel="stylesheet" href="/static/css/uploads.css" />
{% endblock %}
{% block content %}

	
	
	{% if uploaded %}
		
		<div id="normalPrev">
			<div id="uploadImgCont">
				<img id="nImg" src="{{url_for('content', filename=imgSrc)}}" alt="{{imgId}}">
			</div>

			<h2 id="instruct">Center the red dot on the optic disk.<br/>Use the up/down arrow keys to 
				resize the circle.</h2>

			<svg id="focusRing" class="" width="106" height="106">
				<circle id="svgCirc" cx="53" cy="53" r="50" stroke="green" stroke-width="6" fill-opacity="0"/>
				<circle id="svgCenter" cx="53" cy="53" r="4" stroke="red" stroke-width="2" fill-opacity="0"/>
			</svg>

			<button id="submitPosition">Submit Optic Disk Position</button>
			<input type="hidden" id="category" value="{{ category }}">
			
			<div id="loading" class="alert">Processing...</div>

			<div id="continueOptions">
				<a href={{ url_for('uploads.main_route') }}>Back to Uploading</button>
				{% if category != 'control' %}
				<a href="{{url_for('gradeView.main_route', p=imgId)}}"><button>Grade Uploaded Image</button></a>
				{% endif %}
			</div>

		</div>

	{% else %}
		<div id="addPicture">
			<form  method="POST" enctype="multipart/form-data" id="uploadForm">
				<input type="hidden" name="op" value="add">
				<div id="fileCont" class="popUpSection">
					{% set ico = url_for('static', filename='images/ic_file_upload_white_48px.svg') %} 
					<input id="fileField" class="inputfile" type="file" name="img" accept=".png" required>
					<label for="fileField" id="fileFieldLabel"><div id="fileInner"><img src="{{ico}}"><span id="fSpan">Choose a file...<span></div></label>
				</div>
				<div id="popHalfFirst" class="popUpSection pop-half">
					<label for="category">Category: </label>
					<select id="imgType" name="category" required>
						<option value="patient">Patient Image (for grading)</option>
						<option value="control">Control Image</option>
					</select>
				</div>
				<div id="" class="popUpSection pop-half">
					<label for="side">Side: </label>
					<select name="side" id="eye" required>
						<option value="right">Right Eye (OD)</option>
						<option value="left">Left Eye (OS)</option>
					</select>
				</div>
				<div style="clear:both"></div>
				<div id="" class="popUpSection">
					<label for="refName">Reference Name: </label>
					<input id="refName" type="text" name="refName" value="" placeholder="Ex: StudyNumber-PatientId">
				</div>
				<div id="" class="popUpSection">				
					<label for="commentsField">Comments: </label>
					<textarea rows="4" cols="" name="comments" form="uploadForm" id="commentsField"></textarea>
				</div>
				<div id="" class="popUpSection">				
					<input id="upload" type="submit" value="Upload">
				</div>
			</form>
			<div id="uploading" class="alert">Uploading...</div>
			<!--
						<div id="" class="popUpSection">				
					<button id="uploadSubmitBtn" onclick="router('uploadSubmit')">Upload</button>
			</div>
			-->
		</div>
    {% endif %}
	


{% endblock %}


{% block js %}
<script src="{{url_for('static', filename='js/uploads.js')}}"></script>
{% endblock %}

app/templates/userTest.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
	<input id="refName" type="text" name="refName" value="">
	<input id="upload" type="submit" value="Upload">
</form>

{% if thing %}
{{ thing }}
{% endif %}
{% endblock %}